AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'lib/tasks/auto_annotate_models.rake'
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/BlockComments:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  IgnoredMethods: [change]
Metrics/AbcSize:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Layout/LineLength:
  Enabled: false
